---
name: 'GPU Fryer'
on:
  workflow_dispatch:
jobs:
  publish:
    name: 'Base'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: 'Prolog'
        run: |
          apt-cache search apptainer
          apt-cache search singularity
      - name: 'Install Docker CE'
        run: |
          sudo apt update
          #sudo apt install apt-transport-https ca-certificates curl software-properties-common
          #curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          #sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          #apt-cache policy docker-ce
          sudo apt install docker-ce docker-cli
          sudo docker run hello-world
      - name: 'Check Out Repository'
        uses: 'actions/checkout@v4'
        with:
          ref: 'main'
          repository: 'huggingface/gpu-fryer'
      - name: 'Create Docker Image'
        run: |
          ls -al
          docker build -t gpu-fryer .
      - name: 'Upload Artifact'
        uses: 'actions/upload-artifact@v4'
        with:
          name: 'wiki-files'
          path: '**/*.pdf'
