---
name: 'GPU Fryer'
on:
  workflow_dispatch:
jobs:
  publish:
    name: 'Base'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: 'Install Docker CE'
        run: |
          sudo apt-get update
          #sudo apt install apt-transport-https ca-certificates curl software-properties-common
          #curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          #sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          #apt-cache policy docker-ce
          sudo apt install docker-ce
          sudo docker run hello-world
      - name: 'Install Singularity'
        run: |
          sudo apt-get update
          sudo apt install singularity-container
      - name: 'Check Out Repository'
        uses: 'actions/checkout@v4'
        with:
          ref: 'main'
          repository: 'huggingface/gpu-fryer'
      - name: 'Create Docker Image'
        run: |
          ls -ahl Dockerfile
          docker build -t gpu-fryer .
          docker image ls
      - name: 'Create Singularity Image'
        run: |
          singularity pull --name gpu-fryer.sif docker://gpu-fryer:latest
          ls -ahl gpu-fryer.sif
      - name: 'Upload Singularity Image File'
        uses: 'actions/upload-artifact@v4'
        with:
          name: 'singularity-image-file'
          path: 'gpu-fryer.sif'
